cmd/tpch.go
Signed-off-by: Hexilee <i@hexilee.me>
=> Add step, default plan and better plan in error log

cmd/tpch.go, pkg/generator/blank.go, pkg/generator/generator.go, pkg/generator/tpch.go, pkg/horoscope/horoscope.go
```
time="2020-07-06T14:03:05+08:00" level=info msg="complete execution plan7" cost=14346ms query="SELECT /*+ NTH_PLAN(7)*/ nation,o_year,sum(amount) AS sum_profit FROM (SELECT n_name AS nation,..." query id=q9
```
=> Add the query id on log

cmd/query.go, cmd/tpch.go, go.mod, go.sum, pkg/executor/executor.go, pkg/horoscope/data.go, pkg/horoscope/horoscope.go, pkg/horoscope/table.go
```
| ID | #PLAN SPACE | DEFAULT EXECUTION TIME | BEST PLAN EXECUTION TIME | EFFECTIVENESS | BETTER OPTIMAL PLANS         | QUERY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
+----+-------------+------------------------+--------------------------+---------------+------------------------------+--------------------------------------- …
```
=> Add effectiveness report

cmd/generate.go, cmd/hint.go, cmd/main.go, pkg/executor/executor.go, pkg/generator/generator.go
- Generate random value by 'ORDER BY RAND() LIMIT 1'
- Set the default value of the max `numbers` of tables to 3
- Replace 'EXPLAIN' with 'EXPLAIN ANALYZE' in explain subcommand
=> Add subcommand `hint`

cmd/explain.go, pkg/executor/executor.go, pkg/horoscope/card.go, pkg/horoscope/horoscope.go
Besides, we should use `explain` but not `explainAnalyze` to compare whether two plans are same.
=> Update explainAnalyze interface

cmd/generate.go, pkg/generator/generator.go
group generated expression by tables; add flag --rand-logic-op to control generation of logic operator
Signed-off-by: Hexilee <i@hexilee.me>
=> Add control for generation of logic operator

pkg/horoscope/horoscope.go
=> Remove thresholdDiff

cmd/generate.go, pkg/generator/generator.go, pkg/generator/rand.go
replace <=(>=) with <(>) or <=>
Signed-off-by: Hexilee <i@hexilee.me>
=> Fix null comparision bug

README.md, cmd/index.go, pkg/executor/row.go, pkg/horoscope/horoscope.go
=> Fix adding indexes on text or blob columns

pkg/database-types/database_test.go, pkg/executor/explain_test.go
=> Fix failed test case

pkg/horoscope/card.go
=> Fix the card testing

README.md, cmd/bench.go, doc/index_selection.md, pkg/generator/generator.go, pkg/horoscope/card.go
=> doc: add index selection

cmd/generate.go, doc/index_selection.md
=> Update doc and default max tables number for the gen subcommand

cmd/split.go, pkg/database-types/database.go, pkg/database-types/table.go, pkg/generator/rand.go, pkg/horoscope/table.go, pkg/split-data/split.go
=> Fix the split string literal escaped bug

cmd/split.go, pkg/executor/row.go, pkg/split-data/split.go
Signed-off-by: Hexilee <i@hexilee.me>
=> add batch insert for split

pkg/generator/generator.go, pkg/generator/rand.go, pkg/horoscope/horoscope.go
=> queryGen: Remove nullEq operator

cmd/generate.go, pkg/generator/cmp_op.go, pkg/generator/generator.go
=> QueryGen: filter tables

pkg/generator/generator.go
Signed-off-by: hexilee <i@hexilee.me>
=> set SQLCache to true in generating

cmd/generate.go, pkg/generator/generator.go, pkg/util.go
=> QueryGen: add a flag to control whether uses stable order

cmd/bench.go, pkg/horoscope/horoscope.go
=> bench: do verify by default

pkg/generator/range.go, pkg/utils/utils.go
=> QueryGen: fix nulleq bug

pkg/generator/generator.go
=> QueryGen: fix the bug which a table occurs multiple times on the from clause

Makefile, cmd/bench.go, pkg/horoscope/card.go, pkg/horoscope/data.go, pkg/horoscope/horoscope.go, pkg/horoscope/table.go
=> bench: add json format output

pkg/generator/generator.go
Signed-off-by: hexilee <i@hexilee.me>
=> fix a logic bug in RdValuesList

pkg/executor/explain.go, pkg/horoscope/table.go, pkg/utils/utils.go
=> Fix: NaN and INF cannot be marshal

doc/index_selection.md
Signed-off-by: hexilee <i@hexilee.me>
=> update index selection docs

install.sh
As v0.9.2 is released
Signed-off-by: hexilee <i@hexilee.me>
=> upgrade version to 0.9.2 in install.sh

pkg/horoscope/card.go
=> horoscope: fix some bugs in EMQ testing

cmd/options.go, cmd/test.go, pkg/horoscope/horoscope.go
```bash
horo test --ignore-server-error ...
```
This PR adds a flag to resolve below failures:
=> bench: add a flag to ignore server error
